### ISSUE TITLE
User-story #6: Search pill.

### ISSUE THREAD

**Issue by mvp17** [jy-977/ICT-medictionary#6]
As a user I want to search a pill by its name, colour, shape and code, so that I can see its medical information.
Acceptance Criteria: I am on the Start Menu, I click on the Search engine button, it redirects me to a form in which I fill, by dropdowns, the shape and the colour, and by text boxes the code and the name of the desired pill, so I can search whatever pill I want.

**Comment by jy-977** [comment]
6.5
